### // // Obtener todas las publicaciones 
GET  http://localhost:3001/publications HTTP/1.1


### // Buscar publicación por categoría
GET  http://localhost:3001/publications?category=Jugadores HTTP/1.1


### // Buscar publicación por ID
GET  http://localhost:3001/publications/5e240ce1-8dc7-471c-b5f5-9540dcada92c HTTP/1.1




### // // Obtener todos las comentarios 
GET  http://localhost:3001/comments HTTP/1.1


### // Crear un comentario
POST  http://localhost:3001/comments HTTP/1.1
Content-Type: application/json

{ "text": "Prueba comentario" }


### // Actualizar un comentario
PUT http://localhost:3001/comments/1ecf2bd0-292c-46db-bcec-2bd3818e8cac HTTP/1.1
Content-Type: application/json

{ 
  "text": "Nuevo comentario", 
  "like": 0, 
  "unlike": 0 
  }


### // Eliminar un comentario
DELETE  http://localhost:3001/comments/59204859-5ddc-45fd-a9b2-1fd616511a02 HTTP/1.1
